# Generated by Django 3.0.2 on 2020-01-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('has_siblings', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('NR', 'Needs review'), ('RO', 'Reviewed - No decision made'), ('RA', 'Reviewed - Accepted'), ('RR', 'Reviewed - Not Accepted')], default='NR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantGeneMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genemutation', models.CharField(max_length=200)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantEnvironmentalExposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envexposure', models.CharField(max_length=200)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Participant')),
            ],
        ),
    ]
